// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/convert-unit.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/units.ts
var unitCategories = {
  length: {
    name: "Length",
    units: [
      { name: "Millimeter", symbol: "mm", factor: 1e-3 },
      { name: "Centimeter", symbol: "cm", factor: 0.01 },
      { name: "Meter", symbol: "m", factor: 1 },
      { name: "Kilometer", symbol: "km", factor: 1e3 },
      { name: "Inch", symbol: "in", factor: 0.0254 },
      { name: "Foot", symbol: "ft", factor: 0.3048 },
      { name: "Yard", symbol: "yd", factor: 0.9144 },
      { name: "Mile", symbol: "mi", factor: 1609.344 }
    ]
  },
  weight: {
    name: "Weight & Mass",
    units: [
      { name: "Milligram", symbol: "mg", factor: 1e-6 },
      { name: "Gram", symbol: "g", factor: 1e-3 },
      { name: "Kilogram", symbol: "kg", factor: 1 },
      { name: "Metric Ton", symbol: "t", factor: 1e3 },
      { name: "Ounce", symbol: "oz", factor: 0.0283495 },
      { name: "Pound", symbol: "lb", factor: 0.453592 },
      { name: "Stone", symbol: "st", factor: 6.35029 }
    ]
  },
  temperature: {
    name: "Temperature",
    isTemperature: true,
    units: [
      { name: "Celsius", symbol: "C", factor: 1 },
      { name: "Fahrenheit", symbol: "F", factor: 1 },
      { name: "Kelvin", symbol: "K", factor: 1 }
    ]
  },
  area: {
    name: "Area",
    units: [
      { name: "Sq Millimeter", symbol: "mm2", factor: 1e-6 },
      { name: "Sq Centimeter", symbol: "cm2", factor: 1e-4 },
      { name: "Sq Meter", symbol: "m2", factor: 1 },
      { name: "Sq Kilometer", symbol: "km2", factor: 1e6 },
      { name: "Hectare", symbol: "ha", factor: 1e4 },
      { name: "Acre", symbol: "ac", factor: 4046.86 },
      { name: "Sq Foot", symbol: "ft2", factor: 0.092903 }
    ]
  },
  volume: {
    name: "Volume",
    units: [
      { name: "Milliliter", symbol: "mL", factor: 1e-3 },
      { name: "Liter", symbol: "L", factor: 1 },
      { name: "Cubic Meter", symbol: "m3", factor: 1e3 },
      { name: "Gallon (US)", symbol: "gal", factor: 3.78541 },
      { name: "Quart", symbol: "qt", factor: 0.946353 },
      { name: "Pint", symbol: "pt", factor: 0.473176 },
      { name: "Fluid Ounce", symbol: "floz", factor: 0.0295735 }
    ]
  },
  time: {
    name: "Time",
    units: [
      { name: "Millisecond", symbol: "ms", factor: 1e-3 },
      { name: "Second", symbol: "s", factor: 1 },
      { name: "Minute", symbol: "min", factor: 60 },
      { name: "Hour", symbol: "h", factor: 3600 },
      { name: "Day", symbol: "d", factor: 86400 },
      { name: "Week", symbol: "wk", factor: 604800 },
      { name: "Year", symbol: "yr", factor: 31556952 }
    ]
  },
  pressure: {
    name: "Pressure & Stress",
    units: [
      { name: "Pascal", symbol: "Pa", factor: 1 },
      { name: "Kilopascal", symbol: "kPa", factor: 1e3 },
      { name: "Megapascal", symbol: "MPa", factor: 1e6 },
      { name: "Bar", symbol: "bar", factor: 1e5 },
      { name: "PSI", symbol: "psi", factor: 6894.76 },
      { name: "Atmosphere", symbol: "atm", factor: 101325 },
      { name: "mmHg", symbol: "mmHg", factor: 133.322 }
    ]
  },
  force: {
    name: "Force",
    units: [
      { name: "Newton", symbol: "N", factor: 1 },
      { name: "Kilonewton", symbol: "kN", factor: 1e3 },
      { name: "Meganewton", symbol: "MN", factor: 1e6 },
      { name: "Dyne", symbol: "dyn", factor: 1e-5 },
      { name: "Pound-force", symbol: "lbf", factor: 4.44822 },
      { name: "Kilogram-force", symbol: "kgf", factor: 9.80665 }
    ]
  },
  torque: {
    name: "Torque",
    units: [
      { name: "Newton-meter", symbol: "Nm", factor: 1 },
      { name: "Kilonewton-meter", symbol: "kNm", factor: 1e3 },
      { name: "Pound-foot", symbol: "lbft", factor: 1.35582 },
      { name: "Pound-inch", symbol: "lbin", factor: 0.112985 },
      { name: "Kilogram-meter", symbol: "kgm", factor: 9.80665 }
    ]
  },
  energy: {
    name: "Energy & Work",
    units: [
      { name: "Joule", symbol: "J", factor: 1 },
      { name: "Kilojoule", symbol: "kJ", factor: 1e3 },
      { name: "Megajoule", symbol: "MJ", factor: 1e6 },
      { name: "Calorie", symbol: "cal", factor: 4.184 },
      { name: "Kilocalorie", symbol: "kcal", factor: 4184 },
      { name: "Watt-hour", symbol: "Wh", factor: 3600 },
      { name: "Kilowatt-hour", symbol: "kWh", factor: 36e5 },
      { name: "BTU", symbol: "BTU", factor: 1055.06 }
    ]
  },
  power: {
    name: "Power",
    units: [
      { name: "Watt", symbol: "W", factor: 1 },
      { name: "Kilowatt", symbol: "kW", factor: 1e3 },
      { name: "Megawatt", symbol: "MW", factor: 1e6 },
      { name: "Horsepower (metric)", symbol: "hp", factor: 735.499 },
      { name: "Horsepower (imperial)", symbol: "hpI", factor: 745.7 },
      { name: "BTU/hour", symbol: "BTUh", factor: 0.293071 }
    ]
  },
  speed: {
    name: "Speed & Velocity",
    units: [
      { name: "Meter/second", symbol: "m/s", factor: 1 },
      { name: "Kilometer/hour", symbol: "km/h", factor: 0.277778 },
      { name: "Mile/hour", symbol: "mph", factor: 0.44704 },
      { name: "Knot", symbol: "kn", factor: 0.514444 },
      { name: "Foot/second", symbol: "ft/s", factor: 0.3048 }
    ]
  },
  acceleration: {
    name: "Acceleration",
    units: [
      { name: "Meter/second squared", symbol: "m/s2", factor: 1 },
      { name: "Foot/second squared", symbol: "ft/s2", factor: 0.3048 },
      { name: "g (gravity)", symbol: "g", factor: 9.80665 },
      { name: "Gal", symbol: "Gal", factor: 0.01 }
    ]
  },
  data: {
    name: "Digital Storage",
    units: [
      { name: "Bit", symbol: "bit", factor: 0.125 },
      { name: "Byte", symbol: "B", factor: 1 },
      { name: "Kilobyte", symbol: "KB", factor: 1024 },
      { name: "Megabyte", symbol: "MB", factor: 1048576 },
      { name: "Gigabyte", symbol: "GB", factor: 1073741824 },
      { name: "Terabyte", symbol: "TB", factor: 1099511627776 }
    ]
  }
};
var norm = (value) => value.toLowerCase().replace(/[\s·°²³_-]/g, "");
function findUnit(category, query) {
  const q = norm(query);
  return category.units.find((u) => norm(u.symbol) === q || norm(u.name) === q);
}
function convertTemperature(value, from, to) {
  const f = from.toLowerCase()[0];
  const t = to.toLowerCase()[0];
  const celsius = f === "f" ? (value - 32) * (5 / 9) : f === "k" ? value - 273.15 : value;
  return t === "f" ? celsius * (9 / 5) + 32 : t === "k" ? celsius + 273.15 : celsius;
}

// src/lib/mcp/tools/convert-unit.ts
var convert_unit_default = defineTool({
  name: "convert_unit",
  title: "Convert unit",
  description: "Convert a numeric value between two units within a category (length, weight, temperature, pressure, energy, power, and more).",
  inputSchema: {
    category: z.string().describe("Category id, e.g. length, weight, temperature, pressure."),
    value: z.number().describe("The numeric value to convert."),
    from: z.string().describe("Source unit symbol or name, e.g. 'm' or 'Meter'."),
    to: z.string().describe("Target unit symbol or name, e.g. 'ft' or 'Foot'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, value, from, to }) => {
    const key = category.toLowerCase().trim();
    const cat = unitCategories[key];
    if (!cat) {
      return {
        content: [
          {
            type: "text",
            text: `Unknown category "${category}". Available: ${Object.keys(unitCategories).join(", ")}`
          }
        ],
        isError: true
      };
    }
    const fromUnit = findUnit(cat, from);
    const toUnit = findUnit(cat, to);
    if (!fromUnit || !toUnit) {
      return {
        content: [
          {
            type: "text",
            text: `Unknown unit in category "${key}". Available: ${cat.units.map((u) => `${u.symbol} (${u.name})`).join(", ")}`
          }
        ],
        isError: true
      };
    }
    const result = cat.isTemperature ? convertTemperature(value, fromUnit.symbol, toUnit.symbol) : value * fromUnit.factor / toUnit.factor;
    return {
      content: [{ type: "text", text: `${value} ${fromUnit.symbol} = ${result} ${toUnit.symbol}` }],
      structuredContent: { category: key, value, from: fromUnit.symbol, to: toUnit.symbol, result }
    };
  }
});

// src/lib/mcp/tools/list-unit-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_unit_categories_default = defineTool2({
  name: "list_unit_categories",
  title: "List unit categories",
  description: "List every supported unit category and the units available in each, for use with convert_unit.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const categories = Object.entries(unitCategories).map(([id, cat]) => ({
      id,
      name: cat.name,
      units: cat.units.map((u) => ({ symbol: u.symbol, name: u.name }))
    }));
    const text = categories.map((c) => `${c.id} (${c.name}): ${c.units.map((u) => u.symbol).join(", ")}`).join("\n");
    return { content: [{ type: "text", text }], structuredContent: { categories } };
  }
});

// src/lib/mcp/tools/convert-number-base.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var bases = { binary: 2, octal: 8, decimal: 10, hexadecimal: 16 };
var convert_number_base_default = defineTool3({
  name: "convert_number_base",
  title: "Convert number base",
  description: "Convert an integer between binary, octal, decimal and hexadecimal representations.",
  inputSchema: {
    value: z2.string().describe("The number as text, e.g. '1010' or 'ff'."),
    from: z2.enum(["binary", "octal", "decimal", "hexadecimal"]).describe("Base of the input value."),
    to: z2.enum(["binary", "octal", "decimal", "hexadecimal"]).describe("Base of the output value.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ value, from, to }) => {
    const cleaned = value.trim().replace(/^0[bxo]/i, "");
    const parsed = parseInt(cleaned, bases[from]);
    if (!Number.isFinite(parsed)) {
      return {
        content: [{ type: "text", text: `"${value}" is not a valid ${from} number.` }],
        isError: true
      };
    }
    const result = parsed.toString(bases[to]);
    return {
      content: [{ type: "text", text: `${value} (${from}) = ${result} (${to})` }],
      structuredContent: { input: value, from, to, result, decimal: parsed }
    };
  }
});

// src/lib/mcp/tools/base64.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
function encode(text) {
  return btoa(String.fromCharCode(...new TextEncoder().encode(text)));
}
function decode(text) {
  const binary = atob(text.trim());
  const bytes = Uint8Array.from(binary, (c) => c.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}
var base64_default = defineTool4({
  name: "base64",
  title: "Base64 encode / decode",
  description: "Encode text to Base64 or decode a Base64 string back to UTF-8 text.",
  inputSchema: {
    mode: z3.enum(["encode", "decode"]).describe("Whether to encode or decode."),
    text: z3.string().min(1).describe("The text or Base64 string to process.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ mode, text }) => {
    try {
      const result = mode === "encode" ? encode(text) : decode(text);
      return {
        content: [{ type: "text", text: result }],
        structuredContent: { mode, result }
      };
    } catch {
      return {
        content: [{ type: "text", text: "Invalid Base64 input." }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/csv-json.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
function splitLine(line) {
  const out = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (quoted && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else quoted = !quoted;
    } else if (ch === "," && !quoted) {
      out.push(cur);
      cur = "";
    } else cur += ch;
  }
  out.push(cur);
  return out.map((v) => v.trim());
}
function csvToJson(csv) {
  const lines = csv.trim().split(/\r?\n/).filter(Boolean);
  if (lines.length < 2) throw new Error("CSV needs a header row and at least one data row.");
  const headers = splitLine(lines[0]);
  return lines.slice(1).map((line) => {
    const cells = splitLine(line);
    return Object.fromEntries(headers.map((h, i) => [h, cells[i] ?? ""]));
  });
}
function escapeCell(value) {
  const s = value === null || value === void 0 ? "" : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function jsonToCsv(json) {
  const parsed = JSON.parse(json);
  const rows = Array.isArray(parsed) ? parsed : [parsed];
  if (rows.length === 0) return "";
  const headers = Array.from(new Set(rows.flatMap((r) => Object.keys(r ?? {}))));
  return [headers.join(","), ...rows.map((r) => headers.map((h) => escapeCell(r?.[h])).join(","))].join("\n");
}
var csv_json_default = defineTool5({
  name: "csv_json",
  title: "CSV / JSON convert",
  description: "Convert CSV text to a JSON array of objects, or JSON records to CSV text.",
  inputSchema: {
    mode: z4.enum(["csv_to_json", "json_to_csv"]).describe("Direction of the conversion."),
    text: z4.string().min(1).describe("The CSV or JSON source text.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ mode, text }) => {
    try {
      const result = mode === "csv_to_json" ? JSON.stringify(csvToJson(text), null, 2) : jsonToCsv(text);
      return { content: [{ type: "text", text: result }], structuredContent: { mode, result } };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Conversion failed: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/calculate.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
import { create, all } from "npm:mathjs@^15.1.1";
var radMath = create(all, {});
var degMath = create(all, {});
var D = Math.PI / 180;
degMath.import(
  {
    sin: (x) => Math.sin(x * D),
    cos: (x) => Math.cos(x * D),
    tan: (x) => Math.tan(x * D),
    asin: (x) => Math.asin(x) / D,
    acos: (x) => Math.acos(x) / D,
    atan: (x) => Math.atan(x) / D
  },
  { override: true }
);
var calculate_default = defineTool6({
  name: "calculate",
  title: "Calculate expression",
  description: "Evaluate a scientific math expression (arithmetic, trigonometry, logarithms, powers, roots, constants like pi and e).",
  inputSchema: {
    expression: z5.string().min(1).describe("Expression to evaluate, e.g. 'sqrt(2) * sin(pi/4)'."),
    angleUnit: z5.enum(["rad", "deg"]).describe("Angle unit for trigonometric functions. Use 'rad' unless degrees are requested.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ expression, angleUnit }) => {
    try {
      const engine = angleUnit === "deg" ? degMath : radMath;
      const result = engine.evaluate(expression);
      if (typeof result === "function") throw new Error("Expression must produce a value.");
      const text = engine.format(result, { precision: 14 });
      return {
        content: [{ type: "text", text: `${expression} = ${text}` }],
        structuredContent: { expression, angleUnit, result: text }
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Invalid expression: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "converthub-mcp",
  title: "ConvertHub MCP",
  version: "0.1.0",
  instructions: "Privacy-first conversion tools from ConvertHub. Use `list_unit_categories` to discover categories, `convert_unit` for engineering unit conversions, `convert_number_base` for binary/hex/decimal, `base64` for encoding, `csv_json` for data format conversion, and `calculate` to evaluate math expressions. All tools are stateless and store no data.",
  tools: [
    list_unit_categories_default,
    convert_unit_default,
    convert_number_base_default,
    base64_default,
    csv_json_default,
    calculate_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
